### ISSUE TITLE
An idea for an additional principle: Real-World benchmarks

### ISSUE THREAD

**Issue by marclaporte** [db-benchmarks/db-benchmarks#13]
https://github.com/db-benchmarks/db-benchmarks/blob/main/README.md has a wishlist with: "Make it easy to use it in CI, so each new commit is tested and if it's slower than previously the test is not passed"

This is a **great idea**, as it provides a tangible benefit for projects to participate, and each will become better over time.

But we want to make sure projects optimize for Real-World benchmarks. So I wonder if there could there be a general principle that tests should be realistic. This is subjective of course, and reasonable people will disagree. But perhaps it will lead to more different types of tests (each realistic to various use cases). Thus, https://db-benchmarks.com/ provides an even more credible source to find out how each tool does under various realistic scenarios.

Thanks!

**Comment by sanikolaev** [comment]
> I wonder if there could there be a general principle that tests should be realistic

We actually were keeping this in mind when we were preparing the queries. For example we had another test called "synth" which doesn't follow this principle at all since it has just tens of combinations of various data types, logical operators etc. It wasn't open sourced, because it's not realistic at all.

But I didn't include it into the principles list, because I'm not sure we can achieve it and how realistic the current tests are. It's all so subjective. It would be great if we could just take a real-world application and its dataset and query log and build a test based on that, but: 
1.  There are not many people and companies willing to share their actual production query log and corresponding data collections. Probably it's just illegal in many cases (especially for query logs).
2. If you find it, you usually get not a dozen or few of queries, but much more and to visualize it in a compact way (so it's not too difficult to review the results) you need to remove duplicates and similar queries, but doing so automatically makes it subjective and the test becomes less realistic. 

If you can suggest a realistic dataset / query set feel free to make a pull request with a test based on it or just drop me a link.


> Make it easy to use it in CI, so each new commit is tested and if it's slower than previously the test is not passed

What I meant here is that people could use db-benchmarks just as a framework (not a common platform) to run their own tests specific to their applications on their own hardware. In this case it automatically makes it realistic for them. They don't have to open source it, so there's no legal issues. What's needed for that is to make a function / script which compares new test results with previous test results and returns `true` in case everything is ok (the new one is not slower than the previous) or false otherwise, then it can be integrated with any CI: GitLab, Github, CircleCI, Jenkins etc. Everything else is already there:
* you can easily install it
* you can run tests on any hardware
* you can install the UI part too and make it available on your own domain

**Comment by marclaporte** [comment]
Thank you for the thoughtful response.

The first thing that comes to mind: Wikipedia-related data dumps:
https://meta.wikimedia.org/wiki/Data_dumps

**Comment by sanikolaev** [comment]
Right, wikipedia is a popular dataset which comes to mind first, but I'm not sure they share their actual queries.

**Comment by marclaporte** [comment]
So closing for now.

If / when someone comes up with an actionable proposal, we'll be very happy to incorporate in the tests.
